version: '3.7'

services:

  web:
    image: shakhabkhan/yamdb_final
    container_name: web
    restart: always
    volumes:
      - static_data:/usr/src/web/static/
      - nginx_config:/usr/src/web/nginx/
    depends_on:
      - db

  db:
    image: postgres:12.4
    container_name: db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    image: nginx:1.19.3
    restart: always
    container_name: nginx
    volumes:
      - static_data:/usr/src/web/static
      - media_data:/usr/src/web/media
      - nginx_config:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_data:
  media_data:
  nginx_config:
